import { test } from '@playwright/test';
import { ClienteCompletoPage, ClienteCompletoPage } from '../../../pages/cadastro_cliente/cliente_completo/ClienteCompletoPage.js';
import { AnexoPage, AnexoPage } from '../../../pages/cadastro_cliente/cliente_completo/AnexoPage.js';
import { PessoaPage } from '../../../pages/cadastro_cliente/cliente_completo/PessoaPage.js';
import { RefBancariaPage, RefBancariaPage } from '../../../pages/cadastro_cliente/cliente_completo/aba_Referencia/RefBancariaPage.js';
import { RotaPage, RotaPage } from '../../../pages/cadastro_cliente/cliente_completo/RotaPage.js';
import { TelefonePage, TelefonePage } from '../../../pages/cadastro_cliente/cliente_completo/TelefonePage.js';
import { EnderecoPage, EnderecoPage } from '../../../pages/cadastro_cliente/cliente_completo/EnderecoPage.js';

test.describe('Register complete customer', () => {

    test.beforeEach(async ({ page }) => {
        
        CommandsGeneral.login();
        CommandsGeneral.urlAposLogin();
        CommandsGeneral.validateTitlePage();
    })

    context('Register complete customer - basic.', () => {

        test('1.Complete customer CPF.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            GeralClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient(); 
            ClienteCompletoPage.saveClient(); 
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress(); 
            EnderecoPage.modalAdressEmptyValidade(); 
            EnderecoPage.clickOpenTypeAdress(); 
            EnderecoPage.typeAdress(); 
            EnderecoPage.cepAdress(); 
            EnderecoPage.numberAdress(); 
            EnderecoPage.clickSaveAdress(); 
            EnderecoPage.infoAdressAdded(); 
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade(); 
            RotaPage.typeAdressRoute(); 
            RotaPage.routaComplete(); 
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        })  

        test('2.Complete customer CPF - Required fields message.',  async ({ page }) => {
    
            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            ClienteCompletoPage.saveClient(); 
            ClienteCompletoPage.messAlertAdressMandatory(); 
            PessoaPage.cpfClient();
            PessoaPage.nameComplete(); 
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient(); 
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        })  

        test('3.Complete customer CNPJ.',  async ({ page }) => {
    
            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cnpjClient();
            PessoaPage.nameCNPJ();
            PessoaPage.nameFantasyCNPJ();
            ClienteCompletoPage.saveClient(); 
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            ClienteCompletoPage.buttonSaveDisabled()
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        }) 
    })

    context('Register complete customer - Including attachment after saving the customer registration.', () => {

        test('4.Complete customer CPF - happy path.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco()
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded()
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
            ClienteCompletoPage.menuRegisterClientComplete();
            AnexoPage.clickAbaAttachment()  ;
            AnexoPage.validateAbaAttachmentEmpty();
            AnexoPage.selectFirstTypeAttachment();
            AnexoPage.filePDF();
            AnexoPage.confirmSendFile();
            AnexoPage.messAttachmentAddSucess();
            AnexoPage.validateAttachmentAdded();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messRegisterSaveSucess();
        })
    })

    context('Register complete customer - including bank reference.', () => {

        test('5.Complete customer CPF - PIX key type Correct phone number.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixPhone();
            RefBancariaPage.keyPixPhone();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        })  

        test('6.Complete customer CPF - PIX key type Correct email.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled()
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixEmail();
            RefBancariaPage.keyPixEmail();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        }) 

        test('7.Complete customer CPF - PIX key type, correct CPF/CNPJ.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled()
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixCpfCnpj();
            RefBancariaPage.keyPixCPF();
            RefBancariaPage.clicarSalvarRefBanclickSaveRefBankingcaria();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        }) 

        test('8.Complete customer CPF - PIX key type, correct CPF/CNPJ.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled()
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixRandom();
            RefBancariaPage.keyPixRandom();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.modalWaitingLoading();
            ClienteCompletoPage.messRegisterSaveSucess();
        }) 

        test('9.Complete customer CPF - Validate PIX key type. Incorrect phone number.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();

            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixPhone();
            RefBancariaPage.keyPixPhoneWrong();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            RefBancariaPage.messRefBankingKeyPixPhoneInvalid();
        })  

        test('10.Complete customer CPF - Validate PIX key type. Incorrect email.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences() 
            RefBancariaPage.clickAbaRefBanking() ;
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixEmail();
            RefBancariaPage.keyPixEmailWrong();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            RefBancariaPage.messRefBankingKeyPixEmailInvalid();
        })  

        test('11.Complete customer CPF - Validate CPF key type. Incorrect CNPJ.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences() ;
            RefBancariaPage.clickAbaRefBanking() ;
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixCpfCnpj();
            RefBancariaPage.typeKeyPixRandom();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            RefBancariaPage.messRefBankingKeyPixCpfCnpjInvalid();
        })  

        test('12.Complete customer CPF - Validate incorrect Random key type.',  async ({ page }) => {

            ClienteCompletoPage.iconMenuOptions();
            ClienteCompletoPage.optionClientComplete();
            PessoaPage.cpfClient();
            PessoaPage.nameComplete();
            PessoaPage.nameSocial();
            PessoaPage.dateBirth();
            PessoaPage.sexClient();
            ClienteCompletoPage.saveClient();
            ClienteCompletoPage.messAlertAdressMandatory(); 
            EnderecoPage.clickAbaAdress(); 
            EnderecoPage.clickAddNewAdress();
            EnderecoPage.tipoEndereco();
            EnderecoPage.modalAdressEmptyValidade();
            EnderecoPage.clickOpenTypeAdress();
            EnderecoPage.typeAdress();
            EnderecoPage.cepAdress();
            EnderecoPage.numberAdress();
            ClienteCompletoPage.buttonSaveDisabled();
            EnderecoPage.clickSaveAdress();
            EnderecoPage.infoAdressAdded();
            RotaPage.clickAbaRoute(); 
            RotaPage.clickAddedNewRoute();
            RotaPage.modalRouteEmptyValidade();
            RotaPage.typeAdressRoute();
            RotaPage.routaComplete();
            RotaPage.infoRouteAdded();
            TelefonePage.clickAbaPhone(); 
            TelefonePage.clickAddedNewPhone();
            TelefonePage.modalPhoneEmptyValidade();
            TelefonePage.typePhone();
            TelefonePage.numberPhone();
            TelefonePage.ramalPhone();
            TelefonePage.clickSavePhone();
            TelefonePage.infoPhoneAdded();
            TelefonePage.messPhoneAddedSucess();
            ClienteCompletoPage.abaReferences();
            RefBancariaPage.clickAbaRefBanking();
            RefBancariaPage.validateAbaRefBankingEmpty();
            RefBancariaPage.clickAddNewRefBanking();
            RefBancariaPage.modalRefBankingEmpty();
            RefBancariaPage.bank();
            RefBancariaPage.agency();
            RefBancariaPage.account();
            RefBancariaPage.dateOpening();
            RefBancariaPage.phone();
            RefBancariaPage.manager();
            RefBancariaPage.email();
            RefBancariaPage.cpfAccountHolder();
            RefBancariaPage.nameAccountHolder();
            RefBancariaPage.typeAccount();
            RefBancariaPage.operation();
            RefBancariaPage.formPayment();
            RefBancariaPage.typeKeyPixRandom();
            RefBancariaPage.clickSaveRefBanking();
            RefBancariaPage.messRefBankingAddedSucess();
            RefBancariaPage.infoRefBankingAdded();
            ClienteCompletoPage.saveClient();
            RefBancariaPage.messRefBankingKeyPixRandomInvalid();
        })  
    })
})